services:
  app:
    # Ahora usamos la imagen de Docker Hub en lugar de construir localmente en la EC2
    image: ${DOCKERHUB_USERNAME}/centraleats-frontend:${IMAGE_TAG:-latest}
    container_name: centraleats-frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_ADDR=http://98.81.131.147:3001
    restart: always
